/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package purchase.order.system.Management;

import purchase.order.system.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import purchase.order.system.Public.DBConn;

/**
 *
 * @author User
 */
public class SupplierUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form PurchaseRequsition
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public SupplierUI() {
        initComponents();
        
        lblsupplierid.setText("");
        txtsuppliername.setText("");
        txtaddress.setText("");
        txtcity.setText("");
        cmbprovince.setSelectedIndex(0);
        txtpostalcode.setText("");
        txtphone.setText("");
        txtemail.setText("");
        cmbsupplierapproval.setSelectedIndex(0);

        txtsearchbyid.setText("");
        txtsearchbyname.setText("");
        txtsearchbyemail.setText("");

        conn = DBConn.myConn();
        tableload();
       
    }
    
     public boolean tableload() {

        try {

            String sql = "select concat('SUP',supplierId) as 'Supplier ID',supplierName as 'Supplier Name',supplierAddress as 'Address',"
                    + "supplierCity as 'City',supplierProvince as 'Province',supplierPostalCode as 'PostalCode',"
                    + "supplierPhone as 'Phone',supplierEmail as 'Email',supplierApproval as 'Approval' from supplier";
            PreparedStatement pst = DBConn.myConn().prepareStatement(sql);
            rs = pst.executeQuery();
            tblsupplier.setModel(DbUtils.resultSetToTableModel(rs));
            return true;

        } catch (Exception ex) {
            ex.printStackTrace();
            return false;
        }

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblsupplierid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpostalcode = new javax.swing.JTextField();
        cmbprovince = new javax.swing.JComboBox<>();
        txtcity = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtsuppliername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbsupplierapproval = new javax.swing.JComboBox<>();
        txtemail = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtsearchbyemail = new javax.swing.JTextField();
        txtsearchbyname = new javax.swing.JTextField();
        txtsearchbyid = new javax.swing.JTextField();
        btnsearchbyid1 = new javax.swing.JButton();
        btnsearchbyname = new javax.swing.JButton();
        btnsearchbyemail = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsupplier = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnreport = new javax.swing.JButton();

        setBorder(null);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(780, 575));

        jPanel1.setPreferredSize(new java.awt.Dimension(777, 558));

        jPanel3.setBackground(new java.awt.Color(95, 53, 174));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setBackground(new java.awt.Color(23, 2, 74));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(23, 2, 74));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("SUPPLIER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 628, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel1.setText("Supplier ID");

        lblsupplierid.setText("jLabel2");

        jLabel2.setText("Supplier Name");

        jLabel3.setText("Address");

        jLabel4.setText("City");

        jLabel5.setText("Province");

        jLabel6.setText("Postal Code");

        txtpostalcode.setText("jTextField1");

        cmbprovince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- select --", "Northern", "NorthWestern", "Western", "NorthCentral", "Central", "Sabaragamuwa", "Eastern", "Uva", "Southern" }));

        txtcity.setText("jTextField1");

        txtaddress.setText("jTextField1");

        txtsuppliername.setText("jTextField1");

        jLabel10.setText("Phone");

        jLabel11.setText("Email");

        jLabel12.setText("Supplier Approval");

        cmbsupplierapproval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));

        txtemail.setText("jTextField1");

        txtphone.setText("jTextField1");
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphoneKeyTyped(evt);
            }
        });

        jButton1.setText("< Back to Home");

        btnupdate.setText("Update Suppliers");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btninsert.setText("+ Add Suppliers");
        btninsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninsertMouseClicked(evt);
            }
        });
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });

        jLabel13.setText("Search By ID");

        jLabel8.setText("Search By Supplier Name");

        jLabel14.setText("Search By Email");

        txtsearchbyemail.setText("jTextField1");

        txtsearchbyname.setText("jTextField2");

        txtsearchbyid.setText("jTextField1");

        btnsearchbyid1.setText("Filter");
        btnsearchbyid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbyid1ActionPerformed(evt);
            }
        });

        btnsearchbyname.setText("Filter");
        btnsearchbyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbynameActionPerformed(evt);
            }
        });

        btnsearchbyemail.setText("Filter");
        btnsearchbyemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbyemailActionPerformed(evt);
            }
        });

        btnclear.setText("Clear All");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        tblsupplier.setForeground(new java.awt.Color(153, 153, 153));
        tblsupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsupplier);

        btnreport.setText("Generate Report");
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel1)
                            .addGap(38, 38, 38)
                            .addComponent(lblsupplierid)
                            .addGap(489, 489, 489)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel2)
                            .addGap(22, 22, 22)
                            .addComponent(txtsuppliername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(79, 79, 79)
                            .addComponent(jLabel10)
                            .addGap(68, 68, 68)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel3)
                            .addGap(51, 51, 51)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(77, 77, 77)
                            .addComponent(jLabel11)
                            .addGap(76, 76, 76)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel4)
                            .addGap(71, 71, 71)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(77, 77, 77)
                            .addComponent(jLabel12)
                            .addGap(57, 57, 57)
                            .addComponent(cmbsupplierapproval, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbprovince, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpostalcode, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addComponent(btninsert, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(590, 590, 590)
                            .addComponent(btnreport, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98)
                            .addComponent(txtsearchbyid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnsearchbyid1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(txtsearchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnsearchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88)
                            .addComponent(txtsearchbyemail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnsearchbyemail, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(82, 82, 82)
                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(lblsupplierid)
                        .addComponent(jButton1))
                    .addGap(7, 7, 7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtsuppliername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel10))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel11))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(2, 2, 2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel12))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(cmbsupplierapproval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cmbprovince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtpostalcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btninsert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(12, 12, 12)
                    .addComponent(btnreport)
                    .addGap(6, 6, 6)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel13))
                        .addComponent(txtsearchbyid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsearchbyid1))
                    .addGap(7, 7, 7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel8))
                        .addComponent(txtsearchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsearchbyname))
                    .addGap(7, 7, 7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel14))
                        .addComponent(txtsearchbyemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsearchbyemail)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(btnclear)))
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel9MousePressed

    private void txtphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtphoneKeyTyped

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to update?");

        if (x == 0) {
            String supplierId = lblsupplierid.getText();
            String supplierName = txtsuppliername.getText();
            String supplierAddress = txtaddress.getText();
            String supplierCity = txtcity.getText();
            String supplierProvince = cmbprovince.getSelectedItem().toString();
            String supplierPostalCode = txtpostalcode.getText();
            String supplierPhone = txtphone.getText();
            String supplierEmail = txtemail.getText();
            String supplierApproval = cmbsupplierapproval.getSelectedItem().toString();

            //Required Field validation
            if (txtsuppliername.getText().equalsIgnoreCase("") || txtaddress.getText().equalsIgnoreCase("") || txtcity.getText().equalsIgnoreCase("")
                || cmbprovince.getSelectedItem() == "-- select --" || txtpostalcode.getText().equalsIgnoreCase("") || txtphone.getText().equalsIgnoreCase("") || txtemail.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "Please fill the required fields", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //Validtations
            if (ValidateSupplier.checkPhone(txtphone.getText())) {
                //   JOptionPane.showMessageDialog(null, "Please enter valid phone number", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (ValidateSupplier.validateMail(txtemail.getText())) {
                //  JOptionPane.showMessageDialog(null, "wrong format of email", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (ValidateSupplier.validatePostalcode(txtpostalcode.getText())) {
                //  JOptionPane.showMessageDialog(null, "wrong format of postalcode/state", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            SupplierModel sm = new SupplierModel(supplierId, supplierName, supplierAddress, supplierCity, supplierProvince, supplierPostalCode, supplierPhone, supplierEmail, supplierApproval);
            boolean successStatus = sm.updateSupplier();
            if (successStatus) {
                JOptionPane.showMessageDialog(this, "Successfully inserted to db");
                tableload();
                lblsupplierid.setText("");
                txtsuppliername.setText("");
                txtaddress.setText("");
                txtcity.setText("");
                cmbprovince.setSelectedIndex(0);
                txtpostalcode.setText("");
                txtphone.setText("");
                txtemail.setText("");
                cmbsupplierapproval.setSelectedIndex(0);

            } else {
                JOptionPane.showMessageDialog(this, "Error in inserting to db");
            }

        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btninsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninsertMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_btninsertMouseClicked

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:

        String supplierName = txtsuppliername.getText();
        String supplierAddress = txtaddress.getText();
        String supplierCity = txtcity.getText();
        String supplierProvince = cmbprovince.getSelectedItem().toString();
        String supplierPostalCode = txtpostalcode.getText();
        String supplierPhone = txtphone.getText();
        String supplierEmail = txtemail.getText();
        String supplierApproval = cmbsupplierapproval.getSelectedItem().toString();

        //Required Field validation
        if (txtsuppliername.getText().equalsIgnoreCase("") || txtaddress.getText().equalsIgnoreCase("") || txtcity.getText().equalsIgnoreCase("")
            || cmbprovince.getSelectedItem() == "-- select --" || txtpostalcode.getText().equalsIgnoreCase("") || txtphone.getText().equalsIgnoreCase("") || txtemail.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Please fill the required fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Validtations
        if (ValidateSupplier.checkPhone(txtphone.getText())) {
            //JOptionPane.showMessageDialog(null, "Please enter valid phone number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ValidateSupplier.validateMail(txtemail.getText())) {
            //JOptionPane.showMessageDialog(null, "wrong format of email", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (ValidateSupplier.validatePostalcode(txtpostalcode.getText())) {
            // JOptionPane.showMessageDialog(null, "wrong format of postalcode/state", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //System.out.println(supplierName + supplierAddress+supplierCity+supplierProvince+supplierPostalCode+supplierPhone+supplierEmail+supplierApproval);
        
        SupplierModel sm = new SupplierModel(supplierName, supplierAddress, supplierCity, supplierProvince, supplierPostalCode, supplierPhone, supplierEmail, supplierApproval);
        boolean successStatus = sm.insertSupplier();
        if (successStatus) {
            JOptionPane.showMessageDialog(this, "Successfully inserted to database");
            tableload();
            lblsupplierid.setText("");
            txtsuppliername.setText("");
            txtaddress.setText("");
            txtcity.setText("");
            cmbprovince.setSelectedIndex(0);
            txtpostalcode.setText("");
            txtphone.setText("");
            txtemail.setText("");
            cmbsupplierapproval.setSelectedIndex(0);

        } else {
            JOptionPane.showMessageDialog(this, "Error in inserting to db");
        }
    }//GEN-LAST:event_btninsertActionPerformed

    private void btnsearchbyid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbyid1ActionPerformed
        // TODO add your handling code here:

        String searchByID = txtsearchbyid.getText();

        //Button validation
        if (txtsearchbyid.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Field is Empty ! ", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String n = "Select concat('SUP',supplierId) as 'Supplier ID' ,supplierName,supplierAddress,supplierCity,supplierProvince,supplierPostalCode,supplierPhone,supplierEmail,supplierApproval from supplier where supplierId like '%" + searchByID + "%'";

        try {
            pst = conn.prepareStatement(n);
            rs = pst.executeQuery();
            tblsupplier.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnsearchbyid1ActionPerformed

    private void btnsearchbynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbynameActionPerformed
        // TODO add your handling code here:
        String searchByName = txtsearchbyname.getText();

        //Button validation
        if (txtsearchbyname.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Field is Empty ! ", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String n = "Select concat('SUP',supplierId) as 'Supplier ID' ,supplierName,supplierAddress,supplierCity,supplierProvince,supplierPostalCode,supplierPhone,supplierEmail,supplierApproval from supplier where supplierName like '%" + searchByName + "%'";

        try {
            pst = conn.prepareStatement(n);
            rs = pst.executeQuery();
            tblsupplier.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnsearchbynameActionPerformed

    private void btnsearchbyemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbyemailActionPerformed
        // TODO add your handling code here:
        String searchbyemail = this.txtsearchbyemail.getText();
        //Button validation
        if (txtsearchbyemail.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Field is Empty ! ", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String n = "Select concat('SUP',supplierId) as 'Supplier ID' ,supplierName,supplierAddress,supplierCity,supplierProvince,supplierPostalCode,supplierPhone,supplierEmail,supplierApproval from supplier where supplierEmail like '%" + searchbyemail + "%'";

        try {
            pst = conn.prepareStatement(n);
            rs = pst.executeQuery();
            tblsupplier.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnsearchbyemailActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtsearchbyid.setText("");
        txtsearchbyemail.setText("");
        txtsearchbyname.setText("");
        tableload();
    }//GEN-LAST:event_btnclearActionPerformed

    private void tblsupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsupplierMouseClicked
        // TODO add your handling code here:
        int supplier = tblsupplier.getSelectedRow();

        String supplierId = tblsupplier.getValueAt(supplier, 0).toString();
        String supplierName = tblsupplier.getValueAt(supplier, 1).toString();
        String supplierAddress = tblsupplier.getValueAt(supplier, 2).toString();
        String supplierCity = tblsupplier.getValueAt(supplier, 3).toString();
        String supplierProvince = tblsupplier.getValueAt(supplier, 4).toString();
        String supplierPostalCode = tblsupplier.getValueAt(supplier, 5).toString();
        String supplierPhone = tblsupplier.getValueAt(supplier, 6).toString();
        String supplierEmail = tblsupplier.getValueAt(supplier, 7).toString();
        String supplierApproval = tblsupplier.getValueAt(supplier, 8).toString();

        lblsupplierid.setText(supplierId);
        txtsuppliername.setText(supplierName);
        txtaddress.setText(supplierAddress);
        txtcity.setText(supplierCity);
        cmbprovince.setSelectedItem(supplierProvince);
        txtpostalcode.setText(supplierPostalCode);
        txtphone.setText(supplierPhone);
        txtemail.setText(supplierEmail);
        cmbsupplierapproval.setSelectedItem(supplierApproval);
    }//GEN-LAST:event_tblsupplierMouseClicked

     public void B_REPORT_ACTION() {

        try {
            String REPORT = "D:\\Latest CSSE Purchase Order\\Purchase-Order-System\\src\\purchase\\order\\system\\Management\\SupplierReport.jrxml";
            JasperReport JASP_REP = JasperCompileManager.compileReport(REPORT);
            JasperPrint JASP_PRINT = JasperFillManager.fillReport(JASP_REP, null, conn);
            JasperViewer.viewReport(JASP_PRINT);
        } catch (Exception x) {
            System.out.print(x);
        }
    }
    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
        // TODO add your handling code here:
        B_REPORT_ACTION();
    }//GEN-LAST:event_btnreportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btnsearchbyemail;
    private javax.swing.JButton btnsearchbyid1;
    private javax.swing.JButton btnsearchbyname;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbprovince;
    private javax.swing.JComboBox<String> cmbsupplierapproval;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblsupplierid;
    private javax.swing.JTable tblsupplier;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtpostalcode;
    private javax.swing.JTextField txtsearchbyemail;
    private javax.swing.JTextField txtsearchbyid;
    private javax.swing.JTextField txtsearchbyname;
    private javax.swing.JTextField txtsuppliername;
    // End of variables declaration//GEN-END:variables
}
